SET SERVEROUTPUT ON
SET ECHO OFF
WHENEVER SQLERROR CONTINUE

-- === PASO 1: Borrar todo en cascada ===
DROP TABLE PARTIDO      CASCADE CONSTRAINTS PURGE;
DROP TABLE EQUIPO_GRUPO CASCADE CONSTRAINTS PURGE;
DROP TABLE JUGADOR      CASCADE CONSTRAINTS PURGE;
DROP TABLE DIRECTORTECNICO CASCADE CONSTRAINTS PURGE;
DROP TABLE BITACORA     CASCADE CONSTRAINTS PURGE;
DROP TABLE USUARIO      CASCADE CONSTRAINTS PURGE;
DROP TABLE ESTADIO      CASCADE CONSTRAINTS PURGE;
DROP TABLE CIUDAD       CASCADE CONSTRAINTS PURGE;
DROP TABLE PAISANFITRION CASCADE CONSTRAINTS PURGE;
DROP TABLE EQUIPO       CASCADE CONSTRAINTS PURGE;
DROP TABLE CONFEDERACION CASCADE CONSTRAINTS PURGE;
DROP TABLE GRUPO        CASCADE CONSTRAINTS PURGE;

-- === PASO 2: Recrear tablas ===
@sql\ddl.sql

-- === PASO 3: Insertar datos ===
@sql\dml.sql

EXIT
